spring:
  cloud:
    stream:
      bindings:
        input:
          destination: reservations
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'